In [2]:
import torch

In [3]:
randint = torch.randint(-100,100,(6,))
randint

tensor([-28, -56,   5,  36, -20, -86])

In [5]:
tensor = torch.tensor([[0.1, 1.2], [2.2,3.1],[4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [6]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
input = torch.empty(2,3)
input

tensor([[2.0725e+11, 2.0389e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

Sorting in Torch

In [12]:
arrange = torch.arange(5)
arrange

tensor([0, 1, 2, 3, 4])

Constant increments for 5 steps in the range of 3 to 10

In [18]:
linespace = torch.linspace(3,10,steps = 5)
linespace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [19]:
logspace = torch.logspace(start = -10, end=10, steps = 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [20]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
a = torch.empty(2,3)
emptylike = torch.empty_like(a)